# Generated by Django 3.1.7 on 2021-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
